from collections.abc import Sequence
from pathlib import Path
from types import TracebackType
from typing import BinaryIO, Literal, Optional

from numpy import dtype, ndarray
from typing_extensions import Self

class FortranEOFError(TypeError, OSError): ...
class FortranFormattingError(TypeError, OSError): ...

class FortranFile:
    _fp: BinaryIO
    def __init__(self, filename: Path, mode: Literal["r", "w"], header_dtype: dtype) -> None: ...
    def _read_size(self, eof_ok: bool = ...) -> int: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: Optional[type[BaseException]],
        exc_val: Optional[BaseException],
        exc_tb: Optional[TracebackType],
    ) -> None: ...
    def write_record(self, *items: ndarray) -> None: ...
    def read_ints(self, dtype: dtype) -> Sequence[int]: ...
    def read_reals(self, dtype: dtype) -> ndarray: ...
